/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 whenever the process is serving requests. Does not touch the database, so a database outage does not make the process look dead.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 when the database is reachable, migrations are current and a dataset is loaded; otherwise 503 with the failing checks.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List entities
         * @description Companies, industries, countries and economic variables, ordered by name.
         */
        get: operations["list_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an entity */
        get: operations["get_entity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/industries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List industries */
        get: operations["list_industries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List economic variables
         * @description Each variable includes `scenario_rules`: the kinds of change it accepts in a scenario and the limits the API enforces.
         */
        get: operations["list_variables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List relationships
         * @description Curated economic relationships. All are modelling assumptions; see `evidence_level` and `rationale` on each.
         */
        get: operations["list_relationships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relationship-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List relationship types
         * @description The registry that defines what every edge type means.
         */
        get: operations["list_relationship_types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Financial network projection
         * @description All nodes and edges for visualisation: curated economic relationships plus structural links derived from entity attributes, with degree per node and the relationship-type registry for legends.
         */
        get: operations["get_network"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scenarios */
        get: operations["list_scenarios"];
        put?: never;
        /**
         * Create a draft scenario
         * @description Stores scenario *inputs*. Nothing is simulated: `latest_run` stays null until the Phase 4 simulation engine exists.
         */
        post: operations["create_scenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a scenario */
        get: operations["get_scenario"];
        /** Replace a scenario's configuration */
        put: operations["replace_scenario"];
        post?: never;
        /** Delete a scenario */
        delete: operations["delete_scenario"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System status
         * @description Environment, database and migration state, the loaded dataset, and the capabilities this build does and does not have.
         */
        get: operations["system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Capability */
        Capability: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Available */
            available: boolean;
            /**
             * Planned Phase
             * @description Roadmap phase that delivers it, if planned.
             */
            planned_phase: number | null;
            /** Note */
            note: string;
        };
        /**
         * ChangeRuleRead
         * @description A kind of scenario change a variable accepts, with its input limits.
         */
        ChangeRuleRead: {
            change_type: components["schemas"]["ChangeType"];
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
            /** Minimum Exclusive */
            minimum_exclusive: boolean;
            /**
             * Unit Label
             * @example %
             * @example percentage points
             * @example USD per barrel
             */
            unit_label: string;
        };
        /**
         * ChangeType
         * @enum {string}
         */
        ChangeType: "percent_change" | "absolute_change";
        /** CompanyRead */
        CompanyRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Is Fictional
             * @description True for invented entities (all sample companies).
             */
            is_fictional: boolean;
            /**
             * Reference
             * @description Citation for the entity's definition.
             */
            reference: string | null;
            /** Reference Url */
            reference_url: string | null;
            /** Attributes */
            attributes: {
                [key: string]: string | boolean | number;
            };
            /**
             * Dataset Id
             * @description Dataset the record was loaded from (provenance).
             */
            dataset_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "company";
            /** Industry Id */
            industry_id: string;
            /** Country Id */
            country_id: string;
        };
        /** CountryRead */
        CountryRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Is Fictional
             * @description True for invented entities (all sample companies).
             */
            is_fictional: boolean;
            /**
             * Reference
             * @description Citation for the entity's definition.
             */
            reference: string | null;
            /** Reference Url */
            reference_url: string | null;
            /** Attributes */
            attributes: {
                [key: string]: string | boolean | number;
            };
            /**
             * Dataset Id
             * @description Dataset the record was loaded from (provenance).
             */
            dataset_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "country";
            /** Iso Alpha2 */
            iso_alpha2: string;
            /** Currency Code */
            currency_code: string;
        };
        /** DatabaseStatus */
        DatabaseStatus: {
            /**
             * Backend
             * @example sqlite
             * @example postgresql
             */
            backend: string;
            /** Reachable */
            reachable: boolean;
            /** Migration Revision */
            migration_revision: string | null;
            /** Migration Head */
            migration_head: string | null;
            /** Schema Up To Date */
            schema_up_to_date: boolean;
        };
        /** DatasetStatus */
        DatasetStatus: {
            /** Loaded */
            loaded: boolean;
            summary: components["schemas"]["DatasetSummary"] | null;
            /** Entity Counts */
            entity_counts: {
                [key: string]: number;
            };
            /** Relationship Count */
            relationship_count: number;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Is Illustrative */
            is_illustrative: boolean;
            /** Provenance Note */
            provenance_note: string;
            /** License */
            license: string;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /**
             * Loaded At
             * Format: date-time
             */
            loaded_at: string;
        };
        /**
         * EconomicVariablePage
         * @description A page of economic variables.
         */
        EconomicVariablePage: {
            /** Items */
            items: components["schemas"]["EconomicVariableRead"][];
            /**
             * Total
             * @description Total number of items matching the query.
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** EconomicVariableRead */
        EconomicVariableRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Is Fictional
             * @description True for invented entities (all sample companies).
             */
            is_fictional: boolean;
            /**
             * Reference
             * @description Citation for the entity's definition.
             */
            reference: string | null;
            /** Reference Url */
            reference_url: string | null;
            /** Attributes */
            attributes: {
                [key: string]: string | boolean | number;
            };
            /**
             * Dataset Id
             * @description Dataset the record was loaded from (provenance).
             */
            dataset_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "economic_variable";
            /** Unit */
            unit: string;
            value_kind: components["schemas"]["ValueKind"];
            frequency: components["schemas"]["Frequency"];
            category: components["schemas"]["VariableCategory"];
            /**
             * Country Id
             * @description Economy described; null for global benchmarks.
             */
            country_id: string | null;
            /**
             * Scenario Rules
             * @description Which scenario changes this variable accepts, and the enforced limits.
             */
            readonly scenario_rules: components["schemas"]["ChangeRuleRead"][];
        };
        /**
         * EntityKind
         * @enum {string}
         */
        EntityKind: "company" | "industry" | "country" | "economic_variable";
        /** EntityKindPair */
        EntityKindPair: {
            source_kind: components["schemas"]["EntityKind"];
            target_kind: components["schemas"]["EntityKind"];
        };
        /**
         * EntityPage
         * @description A page of entities.
         */
        EntityPage: {
            /** Items */
            items: (components["schemas"]["CompanyRead"] | components["schemas"]["IndustryRead"] | components["schemas"]["CountryRead"] | components["schemas"]["EconomicVariableRead"])[];
            /**
             * Total
             * @description Total number of items matching the query.
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description Stable machine-readable error code.
             * @example not_found
             */
            code: string;
            /**
             * Message
             * @description Human-readable summary, safe to display.
             */
            message: string;
            /** Details */
            details?: components["schemas"]["ErrorDetail"][];
            /**
             * Request Id
             * @description Correlates the error with server logs (X-Request-ID).
             */
            request_id?: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Location
             * @description Part of the request the problem was found in.
             */
            location?: ("body" | "query" | "path" | "header" | "cookie") | null;
            /**
             * Field
             * @description Path of the offending field, e.g. `shocks[0].value`.
             * @example shocks[0].value
             */
            field?: string | null;
            /** Message */
            message: string;
            /**
             * Type
             * @description Machine-readable error type.
             */
            type?: string | null;
        };
        /**
         * ErrorResponse
         * @description Every non-2xx response from the API uses this envelope.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * EvidenceLevel
         * @description How well a relationship is supported. Phase 1 data is entirely ``illustrative``.
         *
         *     * ``illustrative`` — constructed to demonstrate the model; not evidence-based.
         *     * ``documented`` — qualitatively supported by a cited public source.
         *     * ``estimated`` — quantified by a documented statistical estimate.
         *     * ``validated`` — an estimate that has also been validated out of sample.
         * @enum {string}
         */
        EvidenceLevel: "illustrative" | "documented" | "estimated" | "validated";
        /**
         * Frequency
         * @enum {string}
         */
        Frequency: "daily" | "weekly" | "monthly" | "quarterly" | "annual" | "irregular";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /**
         * IndustryPage
         * @description A page of industries.
         */
        IndustryPage: {
            /** Items */
            items: components["schemas"]["IndustryRead"][];
            /**
             * Total
             * @description Total number of items matching the query.
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** IndustryRead */
        IndustryRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Is Fictional
             * @description True for invented entities (all sample companies).
             */
            is_fictional: boolean;
            /**
             * Reference
             * @description Citation for the entity's definition.
             */
            reference: string | null;
            /** Reference Url */
            reference_url: string | null;
            /** Attributes */
            attributes: {
                [key: string]: string | boolean | number;
            };
            /**
             * Dataset Id
             * @description Dataset the record was loaded from (provenance).
             */
            dataset_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "industry";
            /**
             * Classification System
             * @example ISIC Rev. 4
             */
            classification_system: string;
            /**
             * Classification Code
             * @example 51
             */
            classification_code: string;
        };
        /** NetworkNode */
        NetworkNode: {
            /** Id */
            id: string;
            /**
             * Degree
             * @description Number of edges touching this node in the projection.
             */
            degree: number;
            /** Entity */
            entity: components["schemas"]["CompanyRead"] | components["schemas"]["IndustryRead"] | components["schemas"]["CountryRead"] | components["schemas"]["EconomicVariableRead"];
        };
        /** NetworkResponse */
        NetworkResponse: {
            /** @description Null when no dataset has been loaded. */
            dataset: components["schemas"]["DatasetSummary"] | null;
            /** Nodes */
            nodes: components["schemas"]["NetworkNode"][];
            /** Edges */
            edges: (components["schemas"]["RelationshipRead"] | components["schemas"]["StructuralLinkRead"])[];
            /** Relationship Types */
            relationship_types: components["schemas"]["RelationshipTypeRead"][];
            stats: components["schemas"]["NetworkStats"];
        };
        /** NetworkStats */
        NetworkStats: {
            /** Node Count */
            node_count: number;
            /** Edge Count */
            edge_count: number;
            /** Economic Edge Count */
            economic_edge_count: number;
            /** Structural Edge Count */
            structural_edge_count: number;
        };
        /**
         * Polarity
         * @description Assumed direction of effect: does an *increase* in the source raise the target?
         * @enum {string}
         */
        Polarity: "positive" | "negative" | "mixed" | "not_applicable";
        /** ReadinessChecks */
        ReadinessChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * Migrations
             * @enum {string}
             */
            migrations: "up_to_date" | "outdated" | "missing" | "unknown";
            /**
             * Dataset
             * @enum {string}
             */
            dataset: "loaded" | "missing" | "unknown";
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            checks: components["schemas"]["ReadinessChecks"];
        };
        /**
         * RelationshipCategory
         * @enum {string}
         */
        RelationshipCategory: "economic" | "structural";
        /**
         * RelationshipPage
         * @description A page of relationships.
         */
        RelationshipPage: {
            /** Items */
            items: components["schemas"]["RelationshipRead"][];
            /**
             * Total
             * @description Total number of items matching the query.
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * RelationshipRead
         * @description A curated economic relationship — always a model assumption.
         */
        RelationshipRead: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            category: "economic";
            type: components["schemas"]["RelationshipType"];
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            /** @description Assumed effect of an increase in the source on the target measure. */
            polarity: components["schemas"]["Polarity"];
            /** @description Illustrative ordinal strength. */
            strength: components["schemas"]["Strength"];
            evidence_level: components["schemas"]["EvidenceLevel"];
            /**
             * Epistemic Category
             * @description Relationships are modelling assumptions; evidence_level says how well each one is supported.
             * @default assumption
             * @constant
             */
            epistemic_category: "assumption";
            /** Description */
            description: string;
            /**
             * Rationale
             * @description Why the relationship is plausible.
             */
            rationale: string;
            /** Reference */
            reference: string | null;
            /** Dataset Id */
            dataset_id: string;
            /**
             * Directed
             * @description False for symmetric types such as competes_with.
             */
            readonly directed: boolean;
        };
        /**
         * RelationshipType
         * @description Curated relationships stored in the database (economic assertions).
         * @enum {string}
         */
        RelationshipType: "supplies_to" | "lends_to" | "competes_with" | "affects_costs" | "affects_revenue" | "affects_financing" | "influences";
        /** RelationshipTypeRead */
        RelationshipTypeRead: {
            /** Type */
            type: components["schemas"]["RelationshipType"] | components["schemas"]["StructuralLinkType"];
            category: components["schemas"]["RelationshipCategory"];
            /**
             * Label
             * @description Reads as '<source> <label> <target>'.
             */
            label: string;
            /** Description */
            description: string;
            /** Directed */
            directed: boolean;
            /** Has Polarity */
            has_polarity: boolean;
            /** Allowed Pairs */
            allowed_pairs: components["schemas"]["EntityKindPair"][];
        };
        /**
         * ScenarioInput
         * @description Body for creating a scenario, or replacing one with PUT.
         */
        ScenarioInput: {
            /**
             * Name
             * @example Oil price shock
             */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Shocks */
            shocks: components["schemas"]["ShockInput"][];
        };
        /**
         * ScenarioPage
         * @description A page of scenarios.
         */
        ScenarioPage: {
            /** Items */
            items: components["schemas"]["ScenarioRead"][];
            /**
             * Total
             * @description Total number of items matching the query.
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ScenarioRead */
        ScenarioRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            status: components["schemas"]["ScenarioStatus"];
            /** Shocks */
            shocks: components["schemas"]["ShockRead"][];
            /**
             * Latest Run
             * @description Simulation results. Always null in Phase 1: no simulation engine exists yet, and RUMIN never shows results that were not computed.
             */
            latest_run?: null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ScenarioStatus
         * @description Phase 1 only supports drafts. Simulation runs arrive in Phase 4 as a separate
         *     resource, so a scenario's configuration and its results are never conflated.
         * @enum {string}
         */
        ScenarioStatus: "draft";
        /** ShockInput */
        ShockInput: {
            /**
             * Variable Id
             * @example var_brent_crude
             */
            variable_id: string;
            change_type: components["schemas"]["ChangeType"];
            /**
             * Value
             * @description Percent for `percent_change` (30 = +30 %); the variable's unit for `absolute_change` (percentage points for rates).
             * @example 30
             */
            value: number;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ShockRead */
        ShockRead: {
            /** Variable Id */
            variable_id: string;
            change_type: components["schemas"]["ChangeType"];
            /** Value */
            value: number;
            /** Note */
            note: string;
            /**
             * Epistemic Category
             * @default scenario_input
             * @constant
             */
            epistemic_category: "scenario_input";
        };
        /**
         * Strength
         * @description Ordinal, illustrative strength. Deliberately not a precise-looking number.
         * @enum {string}
         */
        Strength: "weak" | "moderate" | "strong";
        /**
         * StructuralLinkRead
         * @description A link derived from an entity attribute, e.g. a company's industry.
         */
        StructuralLinkRead: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            category: "structural";
            type: components["schemas"]["StructuralLinkType"];
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            /**
             * Directed
             * @default true
             */
            directed: boolean;
            /**
             * Derived From
             * @example companies.industry_id
             */
            derived_from: string;
            /** Description */
            description: string;
        };
        /**
         * StructuralLinkType
         * @description Links derived from entity attributes (never stored as relationship rows).
         * @enum {string}
         */
        StructuralLinkType: "in_industry" | "domiciled_in" | "measured_for";
        /** SystemStatus */
        SystemStatus: {
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Api Version */
            api_version: string;
            /** Environment */
            environment: string;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            database: components["schemas"]["DatabaseStatus"];
            dataset: components["schemas"]["DatasetStatus"];
            /** Capabilities */
            capabilities: components["schemas"]["Capability"][];
        };
        /**
         * ValueKind
         * @description How a variable's values behave; determines which scenario changes make sense.
         * @enum {string}
         */
        ValueKind: "price" | "rate" | "exchange_rate" | "index";
        /**
         * VariableCategory
         * @enum {string}
         */
        VariableCategory: "commodity" | "monetary_policy" | "exchange_rate" | "inflation";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_entities: {
        parameters: {
            query?: {
                /** @description Only return this kind. */
                kind?: components["schemas"]["EntityKind"] | null;
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Items to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityPage"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"] | components["schemas"]["IndustryRead"] | components["schemas"]["CountryRead"] | components["schemas"]["EconomicVariableRead"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_industries: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Items to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryPage"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_variables: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Items to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicVariablePage"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_relationships: {
        parameters: {
            query?: {
                /** @description Filter by type. */
                type?: components["schemas"]["RelationshipType"] | null;
                /** @description Only relationships touching this entity. */
                entity_id?: string | null;
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Items to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipPage"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_relationship_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipTypeRead"][];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_network: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkResponse"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_scenarios: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Items to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioPage"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_scenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_scenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replace_scenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_scenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    system_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            /** @description The request contains invalid values. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (details are logged). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
